export * from "./auth.service";
export * from "./teacher-assignment.service";
export * from "./academic-year.service";
export * from "./class.service";
export * from "./school.service";
export * from "./subject.service";
export * from "./teacher-assignment.service";
export * from "./user.service";
export * from './education-level.service'
